### ISSUE TITLE
Error on Complying the itkSuperPixel

### ISSUE THREAD

**Issue by chirayukong** [blowekamp/itkSuperPixel#6]
Hi Braley,

I tried to comply this module to your [ITK repo from your github account](https://github.com/blowekamp/ITK). I got the error: "'vnl_math_min' was not declared in this scope". My CMAKE's version is 3.14.0. I also tried to comply it with the [latest ITK source code](https://github.com/InsightSoftwareConsortium/ITK) but there were missing files in the ITK/Modules/Core/Common/include directory. I also tried to comply it with the ITK version 4.13.1 (released on Aug 8, 2018) and still got the some other errors.

The whole errors from complying with your ITK repo is the followings:

`/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/include/itkSLICImageFilter.hxx:518:103: error: ‘vnl_math_min’ was not declared in this scope
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/include/itkSLICImageFilter.hxx: In instantiation of ‘void itk::SLICImageFilter<TInputImage, TOutputImage, TDistancePixel>::ThreadedPerturbClusters(const OutputImageRegionType&, itk::ThreadIdType) [with TInputImage = itk::Image<float, 2u>; TOutputImage = itk::Image<short unsigned int, 2u>; TDistancePixel = float; itk::SLICImageFilter<TInputImage, TOutputImage, TDistancePixel>::OutputImageRegionType = itk::ImageRegion<2u>; itk::ThreadIdType = unsigned int]’:
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/include/itkSLICImageFilter.hxx:689:59:   required from ‘void itk::SLICImageFilter<TInputImage, TOutputImage, TDistancePixel>::ThreadedGenerateData(const OutputImageRegionType&, itk::ThreadIdType) [with TInputImage = itk::Image<float, 2u>; TOutputImage = itk::Image<short unsigned int, 2u>; TDistancePixel = float; itk::SLICImageFilter<TInputImage, TOutputImage, TDistancePixel>::OutputImageRegionType = itk::ImageRegion<2u>; itk::ThreadIdType = unsigned int]’
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/test/itkSLICImageFilterTest.cxx:140:1:   required from here
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/include/itkSLICImageFilter.hxx:383:59: warning: ‘itk::ThreadIdType itk::ProcessObject::GetNumberOfThreads() const’ is deprecated (declared at /pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/Core/Common/include/itkProcessObject.h:452) [-Wdeprecated-declarations]
   ThreadIdType numberOfThreads = this->GetNumberOfThreads();
                                                           ^
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/include/itkSLICImageFilter.hxx:388:103: warning: ‘itk::ThreadIdType itk::ProcessObject::GetNumberOfThreads() const’ is deprecated (declared at /pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/Core/Common/include/itkProcessObject.h:452) [-Wdeprecated-declarations]
       this->GetNumberOfThreads(), ProcessObject::MultiThreaderType::GetGlobalMaximumNumberOfThreads() );
                                                                                                       ^
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/include/itkSLICImageFilter.hxx:388:103: error: ‘vnl_math_min’ was not declared in this scope
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/include/itkSLICImageFilter.hxx: In instantiation of ‘void itk::SLICImageFilter<TInputImage, TOutputImage, TDistancePixel>::ThreadedConnectivity(const OutputImageRegionType&, itk::ThreadIdType) [with TInputImage = itk::Image<float, 2u>; TOutputImage = itk::Image<short unsigned int, 2u>; TDistancePixel = float; itk::SLICImageFilter<TInputImage, TOutputImage, TDistancePixel>::OutputImageRegionType = itk::ImageRegion<2u>; itk::ThreadIdType = unsigned int]’:
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/include/itkSLICImageFilter.hxx:771:57:   required from ‘void itk::SLICImageFilter<TInputImage, TOutputImage, TDistancePixel>::ThreadedGenerateData(const OutputImageRegionType&, itk::ThreadIdType) [with TInputImage = itk::Image<float, 2u>; TOutputImage = itk::Image<short unsigned int, 2u>; TDistancePixel = float; itk::SLICImageFilter<TInputImage, TOutputImage, TDistancePixel>::OutputImageRegionType = itk::ImageRegion<2u>; itk::ThreadIdType = unsigned int]’
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/test/itkSLICImageFilterTest.cxx:140:1:   required from here
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/include/itkSLICImageFilter.hxx:513:59: warning: ‘itk::ThreadIdType itk::ProcessObject::GetNumberOfThreads() const’ is deprecated (declared at /pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/Core/Common/include/itkProcessObject.h:452) [-Wdeprecated-declarations]
   ThreadIdType numberOfThreads = this->GetNumberOfThreads();
                                                           ^
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/include/itkSLICImageFilter.hxx:518:103: warning: ‘itk::ThreadIdType itk::ProcessObject::GetNumberOfThreads() const’ is deprecated (declared at /pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/Core/Common/include/itkProcessObject.h:452) [-Wdeprecated-declarations]
       this->GetNumberOfThreads(), ProcessObject::MultiThreaderType::GetGlobalMaximumNumberOfThreads() );
                                                                                                       ^
/pghbio/dbmi/batmanlab/chirayu/download/ITK/Modules/External/itkSuperPixel/include/itkSLICImageFilter.hxx:518:103: error: ‘vnl_math_min’ was not declared in this scope
make[2]: *** [Modules/External/itkSuperPixel/test/CMakeFiles/SuperPixelTestDriver.dir/itkSLICImageFilterTest.cxx.o] Error 1
make[1]: *** [Modules/External/itkSuperPixel/test/CMakeFiles/SuperPixelTestDriver.dir/all] Error 2
[ 99%] Building CXX object Modules/Segmentation/LevelSetsv4/test/CMakeFiles/ITKLevelSetsv4TestDriver.dir/itkMultiLevelSetShiImageSubset2DTest.cxx.o
[ 99%] Building CXX object Modules/Segmentation/LevelSetsv4/test/CMakeFiles/ITKLevelSetsv4TestDriver.dir/itkMultiLevelSetMalcolmImageSubset2DTest.cxx.o
[ 99%] Building CXX object Modules/Segmentation/LevelSetsv4/test/CMakeFiles/ITKLevelSetsv4TestDriver.dir/itkLevelSetEvolutionNumberOfIterationsStoppingCriterionTest.cxx.o
[ 99%] Building CXX object Modules/Registration/Metricsv4/test/CMakeFiles/ITKMetricsv4TestDriver.dir/itkMeanSquaresImageToImageMetricv4SpeedTest.cxx.o
[ 99%] Built target ITKOptimizersv4TestDriver
[ 99%] Building CXX object Modules/Registration/Metricsv4/test/CMakeFiles/ITKMetricsv4TestDriver.dir/itkMeanSquaresImageToImageMetricv4VectorRegistrationTest.cxx.o
[ 99%] Linking CXX executable ../../../../bin/ITKLevelSetsv4TestDriver
[ 99%] Linking CXX executable ../../../../bin/ITKMetricsv4TestDriver
[ 99%] Built target ITKRegistrationMethodsv4TestDriver
[ 99%] Built target ITKLevelSetsv4TestDriver
[ 99%] Built target ITKMetricsv4TestDriver
make: *** [all] Error 2`

Thanks a lot.

**Comment by blowekamp** [comment]
This module/filter was integrated in ITKv5. So I recommend using a recent version of ITK and the version of itkSLICImageFilter that comes with it.

**Comment by blowekamp** [comment]
I am archiving this repository to avoid confusion in the future.
